GTModpackTeam/gregtech-expert-2

.github/workflows/beta.yml
- mainブランチにプッシュされた場合に実行されるように
- Pull Requestのマージと単純なPushでトリガーされます
- リリースの方法を変更
- 別のOrganizationでは動作を確認
=> Beta release

manifest.json, modlist.html, overrides/config/NotEnoughEnergistics.cfg, overrides/config/endercore/endercore.cfg, overrides/config/topaddons.cfg, overrides/scripts/_globals.zs, overrides/scripts/recipes/AppliedenErgistics.zs, overrides/scripts/recipes/EnderIO/00_Machines.zs, overrides/scripts/recipes/EnderIO/01_Items.zs, overrides/scripts/recipes/EnderIO/02_Materials.zs, overrides/scripts/recipes/EnderIO/06_Other.zs, overrides/scripts/recipes/EnderIO/_globals.zs, overrides/scripts/recipes/Minecraft.zs
* GTCEu - 2.0.5 -> 2.0.6
* EIO - Soul Powder
* AE - 2k Spatial Component
* EIO
* All liquid craft
* Zombie Generator
* Frank'n'Zombie Generator
* Ender Generator
* Killer Joe
* Experienec Obelisk
* AE - Delete manual creation.
* 1k Storage Component
* 1k Fluid Component
* 2k Spatial Component
=> [update] v0.7.1

manifest.json, modlist.html, overrides/config/chisel.cfg, overrides/config/loottweaker.cfg, overrides/config/opencomputers/gregtechce.recipes, overrides/scripts/loots.zs, overrides/scripts/recipes/Chisel.zs, overrides/scripts/recipes/EnderIO/02_Materials.zs, overrides/scripts/recipes/ForgeMicroblocks.zs, overrides/scripts/recipes/OpenComputers.zs, overrides/scripts/recipes/ProjectRed.zs, overrides/scripts/recipes/VolumetricFlask.zs
* Del - Charcoal
* Del - Coal
* Del - Coal Coke
* Fix - Bookshelfs
* Fix - Glass Pane
* OpenComputer - startup error.
* EIO - Head drop.
* EIO - Totemic Capacitor
* ForgeMicroblocks - All saw and stone rod.
* ProjectRed - Silicon recipe and Electrotine.
* VolumetricFlask - Baffer
=> [update] v0.7.2

manifest.json, modlist.html, overrides/config/loliasm.cfg, overrides/scripts/normal/AppliedenErgistics.zs
* MixinBooter
* CensoredASM
* Printed Calulation Circuit
* Printed Engineering Circuit
* Printed Logic Circuit
* Printed Silicon
=> [hotfix] ae2 & server error

CHANGELOG.md, manifest.json, overrides/config/AppliedEnergistics2/VersionChecker.cfg, overrides/config/gregtech.cfg, overrides/scripts/_Init.zs, overrides/scripts/global/VolumetricFlask.zs, overrides/scripts/normal/AppliedenErgistics.zs, overrides/scripts/normal/BuildingGadgets.zs, overrides/scripts/normal/DankNull.zs, overrides/scripts/normal/EnderIO/02_Materials.zs, overrides/scripts/normal/EnderIO/_materials.zs, overrides/scripts/normal/FluxNetworks.zs, overrides/scripts/normal/GregTech.zs, overrides/scripts/normal/OpenComputers.zs, overrides/scripts/normal/end/AppliedenErgistics.zs
* Disable the glowing setting to reduce TPS to a very low level.
* Creative Energy Cell
* Glass Cable
* Covered Cable
* Smart Cable
* Dense Covered Cable
* Dense Smart Cable
* I shifted the Circuit numbers one by one.
* null mk2
* null mk3
* null mk4
* null mk5
* null mk6
* I shifted the Circuit numbers one by one.
* I shifted the Circuit numbers one by one.
* Change all recipes.
* Vibrant Alloy
* Flux Plug
* Flux Point
* Flux Controller
* Memory Tier1
* Transistor
* ALU
* CU
* I shifted the Circuit numbers one by one.
* Bisphenol A & Diluted Hydrochloric Acid
* Cumene
* Water & Dimethylamine
* 1,1-Dimethylhydrazine & Diluted Hydrochloric Acid
=> [update] v0.13.3

overrides/config/stackie.cfg
=> [Request] ドロップスタックとソート後のスタックについて

overrides/scripts/normal/AppliedEnergistics.zs
The Tooltip designation set for AE2 is different.
* Charger
* Import Bus
* Fluid Import Bus
* Export Bus
* Fluid Export Bus
=> [fix] AE2 tooltip

overrides/scripts/normal/AppliedEnergistics.zs
* Color Applicator
* Paint Ball
=> [del] Paint Ball & Color Applicator

overrides/config/opencomputers/gregtechce.recipes
=> [change] Chunkloader Upgrade

.github/workflows/release.yml
Reverts GTModpackTeam/gregtech-expert-2#114
=> Revert "[update] release.yml"

CHANGELOG.md
* [Fix] Paint Ball & Color Applicator (#113)
* [Update] EIO Brushup (#96)
* [Update] Refresh mods (#111)
* [Update] Chunkloader Upgrade (#112)
* [Update] Quest include v0.9.1 (#117)
* Gregic Probe
* TombManyGraves 2 API
* TombManyPlugins - Cosmetic Armor Reworked
* Smooth Font
* Untranslated Items
* Custom Starter Gear -> FTB Quest
* GraveStone Mod -> TombManyGraves 2
* No Recipe Book -> Crafting Tweaks
* Secure EnderStorage -> Claimed(FTB Utilities)
* Bed Patch
* Better P2P
* Born in a Barn
* Cucumber Library
* FastWorkbench
* FastFurnace
* Fluidlogged API
* Just Enough Characters
* Just Enough Drags
* Mouse Tweaks
* LunatriusCore
* Stackie
* Tips
* B:clientMode=false -> true
* B:ultraLowMemoryUsage=true -> false
* S:title=Minecraft 1.12.2 -> GregTech Expert 2
* …
=> [update] v1.3.0(beta)

overrides/scripts/normal/EnderIO/01_Items.zs
=> [fix] Dark Pickaxe

overrides/scripts/materials.zs, overrides/scripts/normal/GregTech.zs
* Stellar Alloy
* Crystalline Pink Slime(Formula only)
=> [fix] Stellar Alloy & Crystalline Pink Slime

overrides/scripts/normal/AppliedEnergistics.zs, overrides/scripts/normal/ExtraCells.zs, overrides/scripts/normal/Minecraft.zs
* ME Interface
* ME Fluid Interface
* Molecular Assembler
* ME Fluid Assembler
=> [fix] Remove recipe and update

CHANGELOG.md
* [Fix] Dark Pickaxe (#121)
* [Fix] Stellar Alloy & Crystalline Pink Slime (#122)
* [Fix] Modpack cfg (#123)
* [Update] Quest include v0.11.0 (#120)
* [Update] Add Utility Worlds (#124)
* [Update] CEu v2.2.0 (#125)
* [Update] MBT DL (#126)
* Utility Worlds
* Devtech
* Gregicality Multiblocks
* GregTech CE: Unofficial
* GregTech Food Option
* Sledgehammer
* MultiblockTweaker
* CEu Dev team has download it from Github.
* Gregic Probe -> GTCEu
* JEI Integration
* B:enable_starting_items=false -> true
* S:starting_items
> {id:"ftbquests:book",Count:1b,Damage:0s}
> {id:"gregtech:meta_item_1",Count:1b,Damage:465s,tag:{terminal:{_hw:{}}}}
> {id:"gregtech:meta_item_1",Count:1b,Damage:466s,tag:{Charge:100000L}}
> …
=> [update] CHANGELOG.md

overrides/scripts/normal/BuildingGadgets.zs, overrides/scripts/normal/EnderIO/00_Machines.zs
* Basic Capacitor Bank
* Capacitor Bank
* Vibrant Capacitor Bank
* Building Gadget
* Copy-Paste Gadget
* Exchanging Gadget
* Destruction Gadget
=> [hotfix] OreDictionary for batteries

overrides/scripts/normal/BuildingGadgets.zs
* The CIRCUIT BOARD used in the recipe is different.
=> [fix] circuit board

overrides/scripts/normal/ArchitectureCraft.zs, overrides/scripts/normal/EnderIO/01_Items.zs, overrides/scripts/normal/ForgeMicroblocks.zs
* Hammer
* Dark Steel Upgrade "Micro Anvil"
* Dark Steel Upgrade "Mini Anvil"
* Dark Steel Upgrade(XP) "Mini Anvil"
* Stone Saw
* Iron Saw
* Diamond Saw
=> [fix] Recipes using Stick Wood

overrides/config/opencomputers/gregtechce.recipes
* Fixed a recipe that could no longer be created with the CEu update.
=> [fix] Cannot create

overrides/scripts/normal/EnderIO/05_Other.zs
* Nutrient Distillation
* Dew of Void
* Fire Water
* Sunshine
* Cloud Seed
* Concentrated Cloud
=> [fix] EIO Liquid

overrides/scripts/normal/EZStorage.zs
* Blank Box
* Storage Core
* Storage Box
* Condensed Storage Box
* Super Storage Box
* Ultra Storage Box
* Hyper Storage Box
* Input Port
* Output Port
* Extract Port
* Crafting Box
* Search Box
=> [add] EZStorage assembler recipes

overrides/scripts/normal/Minecraft.zs
* Redstone Lamp
* Duplicate recipe with AE Dense Cables
=> [fix] Redstone Lamp

overrides/scripts/materials.zs, overrides/scripts/normal/EnderIO/02_Materials.zs, overrides/scripts/normal/GregTech.zs
=> [fix] Molten Soularium

overrides/scripts/normal/AppliedEnergistics.zs, overrides/scripts/normal/ExtraCells.zs
* Storage Housing
* Level Emitter
* Fluid Level Emitter
* Storage Bus
* Fluid Storage Bus
* OreDict Storage Bus
* Toggle Bus
* Fluid Housing
* Advanced Storage Housing
=> [add] AE2 assembler recipes

overrides/scripts/normal/EnderIO/00_Machines.zs, overrides/scripts/normal/EnderIO/03_Blocks.zs, overrides/scripts/normal/EnderIO/_globals.zs
=> [add] EIO Painter

CHANGELOG.md, README.md, manifest.json, overrides/resources/modpack/lang/ja_jp.lang
* [Update] Cable anchor (#151)
* [Update] EZStorage assembler recipes (#155)
* [Update] AE2 assembler recipes (#154)
* [Update] EIO Painter (#162)
* [Fix] Charged Certus Quartz Crystal (#153)
* [Fix] Redstone Lamp (#157)
* [Fix] Molten Soularium (#159)
* Had Enough Items
* SuperMartijn642's Core Lib
* Trash Cans
* Cable Anchor
* Charged Certus Quartz Crystal
* Changed to not require distilled water
* Molten Soularium
* Painter
* Redstone Lamp
* Duplicate recipe with AE Dense Cables
* Storage Housing
* Level Emitter
* Fluid Level Emitter
* Storage Bus
* Fluid Storage Bus
* OreDict Storage Bus
* Toggle Bus
* Fluid Housing
* Advanced Storage Housing
* Blank Box
* Storage Core
* Storage Box
* Condensed Storage Box
* Super Storage Box
* Ultra Storage Box
* Hyper Storage Box
* Input Port
* …
=> [update] v1.8.0

manifest.json, modlist.html
Reverts GTModpackTeam/gregtech-expert-2#165
=> Revert "[update] CensoredASM"

overrides/resources/gregtech/lang/ja_jp.lang
CEu 2.2.2-betaに対応しました
Integrated Processorのtooltipを修正しました
=> Update CEu 2.2.2 beta

overrides/scripts/normal/AppliedEnergistics.zs
Discordで指摘されたので作成
Annihilation Coreなどと同様に倍作れるようにしておきました
=> add pure certus quartz recipe for the blank pattern

manifest.json
* LoliASM
* Devtech
* GregTech Food Option
* Had Enough Items
=> [update] CEu mods

manifest.json, modlist.html
=> [add] Better P2P

CHANGELOG.md, manifest.json
* [Update] CEu mods (#178)
* [Update] CEu 2.3.1 (#181) 
* [Update] Better P2P (#180)
* [Fix] EIO duplication recipes (#156)
* Better P2P
* GregTech CE: Unofficial
* LoliASM
* DevTech
* GregTech Food Option
* Had Enough Items
* Sludge
* Unheated Cane Syrup
=> [update] v1.9.2

manifest.json
=> [update] AE2 & Better P2P

manifest.json, overrides/scripts/multiblock/32000_Greenhouse.zs
=> [update] GTFO v1.6.1

manifest.json, modlist.html
* SuperMartijn642's Core Lib
* Trash Cans
=> [del] Trash Cans

overrides/scripts/normal/CatWalks.zs, overrides/scripts/normal/Chisel.zs, overrides/scripts/normal/GregTech.zs, overrides/scripts/normal/Minecraft.zs
* Vanilla's Bookshelfs is now compatible with ore dictionaries.
* Classic Support Cables
* Bookshelfs
=> [fix] recipe duplication

overrides/scripts/normal/EnderIO/02_Materials.zs
=> [update] Conduit Binder cost down

overrides/scripts/normal/AppliedEnergistics.zs
=> [add] Crafting Unit assembler recipe

overrides/config/loliasm.cfg
* onDemandAnimatedTextures=true -> false
=> [update] onDemandAnimatedTextures

manifest.json, overrides/scripts/multiblock/32000_Greenhouse.zs
Reverts GTModpackTeam/gregtech-expert-2#189
=> Revert "[update] GTFO v1.6.1"

CHANGELOG.md, manifest.json
* [Update] AE2 & Better P2P (#190)
* [Update] Conduit Binder cost down (#183)
* [Update] Crafting Unit assembler recipe (#184)
* [Update] onDemandAnimatedTextures (#192)
* [Fix] Classic Support Cables (#191)
* Better P2P
* Crafting Unit
* Vanilla Bookshelves is now compatible with ore dictionaries.
* Conduit Binder
* Classic Support Cables
* Bookshelves
=> [update] v1.9.3

manifest.json, overrides/scripts/multiblock/32000_Greenhouse.zs, overrides/scripts/normal/GregTechFoodOption.zs
=> [update] GTFO v1.6.2

overrides/scripts/normal/GregTech.zs, overrides/scripts/normal/OpenComputers.zs, overrides/scripts/normal/end/AppliedenErgistics.zs, overrides/scripts/normal/end/EnderIO.zs, overrides/scripts/normal/end/Gregtech.zs, overrides/scripts/normal/end/ModPack.zs
=> [fix] /gt recipecheck

overrides/config/mod-director/gcys.url.json
* Gregicality Science(modified by Quarri)
=> [update] GCY:S

CHANGELOG_v2.md
* Inventory Sorter -> Inventory Bogo Sorter
* Gregicality Science(modified by Quarri)
* LootTweaker
* ModularUI
* B:searchAdvancedTooltips=false -> true
* searchadvancedtooltips{ B:search=false -> true }
* Creative Energy Cell
* Creative Capacitor Bank
* GTE ME Storage Fake Component
=> [update] 2.2.0-pr CHANGELOG

overrides/scripts/normal/AEAdditions.zs, overrides/scripts/normal/end/ModPack.zs
=> [fix] Neutronium to Orichalcum
